name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  go_router: ^14.3.0
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_bloc: ^8.1.6
  geolocator: ^9.0.2
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_database: ^11.3.1
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/weatherIcon.png
    - assets/sky.jpg
    - assets/rain.png
    - assets/icons/png/lluvia.png
    - assets/icons/png/lluvia_debil.png
    - assets/icons/png/nieve.png
    - assets/icons/png/nublado.png
    - assets/icons/png/soleado.png
    - assets/icons/png/poco_nublado.png
    