// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtsqyFpyQ_Ejil-WzC364PvCk8Ksbi2-s',
    appId: '1:668343687479:web:3f4686c6290702bc14a2b2',
    messagingSenderId: '668343687479',
    projectId: 'weather-firebase-2319f',
    authDomain: 'weather-firebase-2319f.firebaseapp.com',
    databaseURL: 'https://weather-firebase-2319f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'weather-firebase-2319f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRsLJQnGtYcb-gVuiB686X62dDD9JBIUY',
    appId: '1:668343687479:android:f573a979547e0cba14a2b2',
    messagingSenderId: '668343687479',
    projectId: 'weather-firebase-2319f',
    databaseURL: 'https://weather-firebase-2319f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'weather-firebase-2319f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVCYVMJnAosSNuItK07K1_TOJzXMnp5II',
    appId: '1:668343687479:ios:3ba07f77583a25f014a2b2',
    messagingSenderId: '668343687479',
    projectId: 'weather-firebase-2319f',
    databaseURL: 'https://weather-firebase-2319f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'weather-firebase-2319f.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVCYVMJnAosSNuItK07K1_TOJzXMnp5II',
    appId: '1:668343687479:ios:3ba07f77583a25f014a2b2',
    messagingSenderId: '668343687479',
    projectId: 'weather-firebase-2319f',
    databaseURL: 'https://weather-firebase-2319f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'weather-firebase-2319f.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtsqyFpyQ_Ejil-WzC364PvCk8Ksbi2-s',
    appId: '1:668343687479:web:772c6cde460ef81f14a2b2',
    messagingSenderId: '668343687479',
    projectId: 'weather-firebase-2319f',
    authDomain: 'weather-firebase-2319f.firebaseapp.com',
    databaseURL: 'https://weather-firebase-2319f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'weather-firebase-2319f.firebasestorage.app',
  );

}